# Make sure to check the documentation at http://goreleaser.com
project_name: crmon
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- binary: crmon
  main: ./cmd/crmon
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.build={{.ShortCommit}} -X main.date={{.Date}}
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
